"""production_workflows

Revision ID: b77ffc86066b
Revises: 0002
"""

from alembic import op
import sqlalchemy as sa


revision = "b77ffc86066b"
down_revision = "0002"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dead_letters",
        sa.Column("source_key", sa.String(length=180), nullable=False),
        sa.Column("envelope", sa.JSON(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_key"),
    )
    op.create_index(op.f("ix_dead_letters_created_at"), "dead_letters", ["created_at"], unique=False)
    op.create_table(
        "domain_projections",
        sa.Column("aggregate_id", sa.String(length=64), nullable=False),
        sa.Column("consumer", sa.String(length=64), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("updated_at", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("aggregate_id", "consumer"),
    )
    op.create_table(
        "agent_runs",
        sa.Column("execution_id", sa.String(length=64), nullable=False),
        sa.Column("agent", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("duration_ms", sa.Float(), nullable=False),
        sa.Column("detail", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["execution_id"],
            ["agent_executions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_agent_runs_agent"), "agent_runs", ["agent"], unique=False)
    op.create_index(op.f("ix_agent_runs_created_at"), "agent_runs", ["created_at"], unique=False)
    op.create_index(op.f("ix_agent_runs_execution_id"), "agent_runs", ["execution_id"], unique=False)
    op.create_table(
        "notifications",
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("event_id", sa.String(length=64), nullable=False),
        sa.Column("order_id", sa.String(length=64), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("read", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id"),
    )
    op.create_index(op.f("ix_notifications_created_at"), "notifications", ["created_at"], unique=False)
    op.create_index(op.f("ix_notifications_user_id"), "notifications", ["user_id"], unique=False)
    op.create_table(
        "return_items",
        sa.Column("return_id", sa.String(length=64), nullable=False),
        sa.Column("order_item_id", sa.String(length=64), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.CheckConstraint("quantity > 0 AND amount >= 0"),
        sa.ForeignKeyConstraint(
            ["order_item_id"],
            ["order_items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["return_id"],
            ["returns.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("return_id", "order_item_id"),
    )
    op.create_index(op.f("ix_return_items_created_at"), "return_items", ["created_at"], unique=False)
    op.create_index(op.f("ix_return_items_order_item_id"), "return_items", ["order_item_id"], unique=False)
    op.create_index(op.f("ix_return_items_return_id"), "return_items", ["return_id"], unique=False)
    op.add_column(
        "order_items", sa.Column("returned_quantity", sa.Integer(), server_default="0", nullable=False)
    )
    op.add_column("orders", sa.Column("procurement", sa.JSON(), server_default="{}", nullable=False))
    op.create_index(op.f("ix_refunds_order_id"), "refunds", ["order_id"], unique=False)
    op.add_column("returns", sa.Column("amount", sa.Integer(), server_default="0", nullable=False))
    op.create_index(op.f("ix_returns_order_id"), "returns", ["order_id"], unique=False)
    convention = {"uq": "uq_%(table_name)s_%(column_0_name)s"}
    for table, columns in [
        ("returns", ["order_id"]),
        ("refunds", ["order_id"]),
        ("shipments", ["order_id", "kind"]),
    ]:
        constraints = sa.inspect(op.get_bind()).get_unique_constraints(table)
        for constraint in constraints:
            if constraint["column_names"] == columns:
                name = constraint["name"] or f"uq_{table}_{columns[0]}"
                with op.batch_alter_table(table, naming_convention=convention) as batch:
                    batch.drop_constraint(name, type_="unique")
    with op.batch_alter_table("order_items") as batch:
        batch.create_check_constraint(
            "ck_returned_quantity", "returned_quantity >= 0 AND returned_quantity <= quantity"
        )
    # Preserve legacy whole-order return entitlements and amounts.
    op.execute(
        "UPDATE order_items SET returned_quantity=quantity WHERE order_id IN (SELECT order_id FROM returns)"
    )
    op.execute("UPDATE returns SET amount=(SELECT total FROM orders WHERE orders.id=returns.order_id)")
    # ### end Alembic commands ###


def downgrade():
    connection = op.get_bind()
    if connection.execute(sa.text("SELECT count(*) FROM return_items")).scalar():
        raise RuntimeError(
            "Item returns exist. Restore a tested pre-upgrade backup instead of destructive downgrade."
        )
    with op.batch_alter_table("order_items") as batch:
        batch.drop_constraint("ck_returned_quantity", type_="check")
    for table, columns in [
        ("returns", ["order_id"]),
        ("refunds", ["order_id"]),
        ("shipments", ["order_id", "kind"]),
    ]:
        with op.batch_alter_table(table) as batch:
            batch.create_unique_constraint(f"uq_{table}_{columns[0]}", columns)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_returns_order_id"), table_name="returns")
    op.drop_column("returns", "amount")
    op.drop_index(op.f("ix_refunds_order_id"), table_name="refunds")
    op.drop_column("orders", "procurement")
    op.drop_column("order_items", "returned_quantity")
    op.drop_index(op.f("ix_return_items_return_id"), table_name="return_items")
    op.drop_index(op.f("ix_return_items_order_item_id"), table_name="return_items")
    op.drop_index(op.f("ix_return_items_created_at"), table_name="return_items")
    op.drop_table("return_items")
    op.drop_index(op.f("ix_notifications_user_id"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_created_at"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(op.f("ix_agent_runs_execution_id"), table_name="agent_runs")
    op.drop_index(op.f("ix_agent_runs_created_at"), table_name="agent_runs")
    op.drop_index(op.f("ix_agent_runs_agent"), table_name="agent_runs")
    op.drop_table("agent_runs")
    op.drop_table("domain_projections")
    op.drop_index(op.f("ix_dead_letters_created_at"), table_name="dead_letters")
    op.drop_table("dead_letters")
    # ### end Alembic commands ###
